server:
  port: 8080
spring:
  datasource:
    username: skillbox
    password: skillbox
    url: jdbc:postgresql://localhost:5432/search_engine
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/master.xml
    enabled: true
    drop-first: false
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
    show-sql: false
logging:
  level:
    root: info
    searchengine.services.management.Node: error
    searchengine.services.management.NodePageExplorer: error
indexing-settings:
  sites:
    - url: https://www.svetlovka.ru/
      name: СВЕТЛОВКА молодежная библиотека
    - url: https://playback.ru/
      name: Интернет магазин Playback.RU
    - url: https://sendel.ru/
      name: Sendel Site
  lemma-threshold: 70 #in percents
  user-agent: DavydoffSearchBot
  referrer: http://www.google.com